import Head from 'next/head'
import {BsFillMoonStarsFill} from 'react-icons/bs'
import {AiFillLinkedin, AiFillGithub} from "react-icons/ai"
import { SiLeetcode } from "react-icons/si";
import Image from 'next/image'
import deved from "../../public/dev-ed-wave.png"
import design from '../../public/design.png'
import code from '../../public/code.png'
import consulting from '../../public/consulting.png'
import web1 from '../../public/web1.png'
import web2 from '../../public/web2.png'
import web3 from '../../public/web3.png'
import web4 from '../../public/web4.png'
import web5 from '../../public/web5.png'
import web6 from '../../public/web6.png'
import { useState } from 'react'

export default function Home() {
  const [darkMode, setDarkMode]=useState(true)
  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Mohammad Alfayoume Portofolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='bg-white px-10 md:px-20 lg:px-40 dark:bg-gray-900'>
        <section className='min-h-screen'>
          <nav className='py-10 mb-12 flex justify-between dark:text-white'>
            <h1 className='text-xl font-burtons'>portofolio</h1>
            <ul className='flex items-center'>
              <li>
                <BsFillMoonStarsFill onClick={()=>setDarkMode(!darkMode)} className='cursor-pointer text-2xl'/>
              </li>
              <li><a className='bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md ml-8' href='https://drive.google.com/file/d/1V0_6X7KkUFjNPugIsAxTkOPKPwbS0FeA/view?usp=sharing' target='_blank'>Resume</a></li>
            </ul>
          </nav>
          <div className='text-center p-10'>
            <h2 className='text-5xl py-2 text-teal-600 font-medium md:text-6xl dark:text-teal-400'>Mohammad Alfayoume</h2>
            <h3 className='text-2xl py-2 md:text-3xl dark:text-white'>Full-stack web developer</h3>
            <p className='text-md py-5 leading-8 text-gray-800 md:text:xl max-w-lg mx-auto dark:text-gray-200'>
            Full-Stack Web Developer with a background in mechanical engineering. interested and passionate about software development. always looking for new ways for improvement, skills, and knowledge ways. Curious, passionate, highly motivated, fast learner.
            </p>
          </div>
          <div className='text-5xl flex justify-center gap-16 py-3 text-gray-600 dark:text-gray-400'>
            <a href='https://leetcode.com/mabed3819/' target='_blank'><SiLeetcode /></a>
            <a href='https://www.linkedin.com/in/mohammad-alfayoume-194b531b3/' target='_blank'><AiFillLinkedin /></a>
            <a href='https://github.com/mohammadalfayoume' target='_blank'><AiFillGithub /></a>
          </div>
          <div className='relative mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 mt-20 overflow-hidden md:h-96 md:w-96'>
            <Image src={deved} layout='fill' objectFit='cover' />
          </div>
        </section>

        <section>
          <div>
            <h3 className='text-3xl py-1 dark:text-white'>Technical Skills</h3>
          </div>
          <div className='lg:flex gap-10'>
            <div className='text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white flex-1'>
              <Image className='mx-auto' src={require("../../public/front.png")} width={100} height={100} />
              <h3 className='text-lg font-medium pt-8 pb-2'>Front-End</h3>
              <h4 className='py-4 text-teal-600'>Technologies I use</h4>
              <p className='text-gray-800 py-1'>HTML && CSS && JavaScript</p>
              <p className='text-gray-800 py-1'>React.js</p>
              <p className='text-gray-800 py-1'>Next.js</p>
              <p className='text-gray-800 py-1'>React-Bootstrap</p>
              <p className='text-gray-800 py-1'>Tailwindcss</p>
            </div>
            <div className='text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white flex-1'>
              <Image className='mx-auto' src={require("../../public/back.png")} width={100} height={100} />
              <h3 className='text-lg font-medium pt-8 pb-2'>Back-End</h3>
              
              <h4 className='py-4 text-teal-600'>Technologies I use</h4>
              <p className='text-gray-800 py-1'>Node.js</p>
              <p className='text-gray-800 py-1'>Express</p>
              <p className='text-gray-800 py-1'>Django</p>
            </div>
            <div className='text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white flex-1'>
              <Image className='mx-auto' src={require("../../public/database.png")} width={100} height={100} />
              <h3 className='text-lg font-medium pt-8 pb-2'>Database</h3>
              <h4 className='py-4 text-teal-600'>Technologies I use</h4>
              <p className='text-gray-800 py-1'>MongoDB && Mongoose</p>
              <p className='text-gray-800 py-1'>SQL</p>
              <p className='text-gray-800 py-1'>SQLite</p>
              <p className='text-gray-800 py-1'>PostgreSQL</p>
            </div>
          </div>
        </section>
        <section>
          <div>
            <h3 className='text-3xl py-1 dark:text-white'>Projects</h3>
            <p className='text-md py-2 leading-8 text-gray-80 dark:text-gray-200'>Since the beginning of my journey as a web
            developer, I've done three projects I would like to shere them with you.</p>
          </div>
          <div className='lg:flex gap-10'>
            <div className='text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white flex-1'>
              <Image className='mx-auto' src={require("../../public/candidate.png")} width={100} height={100} />
              <h3 className='text-lg font-medium pt-8 pb-2'>ReqruitIQ</h3>
              <p className='py-2'>ReqruitIQ is a web application to simplify the candidate selection and hiring process for employers and job seekers. Companies can register, search, and view candidate profiles while job seekers can track company views, manage interview details, and compare their profiles to other candidates.</p>
              <h4 className='py-4 text-teal-600'>Technologies: Reactjs, Django, PostgreSQL, React-Bootstrap, CSS, Tailwind</h4>
              <a className='text-5xl flex justify-center gap-16 py-3 text-gray-600 dark:text-gray-400' href='https://github.com/orgs/401-Jobs/repositories' target='_blank'><AiFillGithub /></a>
            </div>
            <div className='text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white flex-1'>
              <Image className='mx-auto' src={require("../../public/AI.png")} width={100} height={100} />
              <h3 className='text-lg font-medium pt-8 pb-2'>Snake Game with AI</h3>
              <p className='py-2'>Snake game with two options, either playing by keyboard or
playing with camera using Artificial Intelligence and Machine
Learning.
</p>
              <h4 className='py-4 text-teal-600'>Technologies: Pygame, Tkinter, CVZone, Mediapipe</h4>
              <a className='text-5xl flex justify-center gap-16 py-3 text-gray-600 dark:text-gray-400' href='https://github.com/Snake-Game-with-AI-Project/Snack-Game-with-AI' target='_blank'><AiFillGithub /></a>
            </div>
            <div className='text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white flex-1'>
              <Image className='mx-auto' src={require("../../public/news.png")} width={100} height={100} />
              <h3 className='text-lg font-medium pt-8 pb-2'>News Live</h3>
              <p className='py-2'>Full stack web application shows the latest news in the
world with community section that make authenticate
people more interact with other people by publish their
posts and see the news of others.</p>
              <h4 className='py-4 text-teal-600'>Technologies: Reactjs, Nodejs, Express, MongoDB,
mongoose, Auth0, React-Bootstrap, CSS, JSX</h4>
              <a className='text-5xl flex justify-center gap-16 py-3 text-gray-600 dark:text-gray-400' href='https://github.com/orgs/Code-Fellow-301-Project/repositories' target='_blank'><AiFillGithub /></a>
            </div>
          </div>
        </section>
      </main>
    </div>
  )
}
